### ISSUE TITLE
APT crashing

### ISSUE THREAD

**Issue by JeffLaramy** [jDeters-USACE/Antecedent-Precipitation-Tool#22]
Our wetland and soils scientists are using the new version of the tool (v1.0.20) and it keeps crashing.  It ran successfully a few times, but lately they have been getting this message.  They had no issues with the previous version of APT
![Capture](https://user-images.githubusercontent.com/35583912/186457617-3d1d51cb-f76f-4836-a2a7-a6e503f68b1e.JPG)

**Comment by jlgutenson** [comment]
Hey Jeff, 

I'm closing this issue since our email correspondence covered things. 

For posterity, it does appear that there is a large data gap in the dataset and I think I understand why the APT was working and then stopped working with the latest version. The current APT will not allow for more than 15 weather stations to be used to construct the historical precipitation record. We had a bug in the previous version that was allowing for more than 15 weather stations to be used to build the climatology. I suspect that’s why you were seeing those issues with the printout. The stations table won’t size appropriately for more than 15 weather stations. 

We fixed the 15 stations bug and it seems your observation points have feel victim to that 15 station cut off. Unfortunately, there isn’t an easy fix or workaround in the current version of the APT. The merged_stations_converted_to_in_2022-07-14.csv file should be present in your “Outputs” folder and you could manually fill in the missing precipitation values from another local weather station that has the data, you would just have to find an alternative means to generate the print out. 

Thanks again for reaching out!

-Joseph

**Comment by JeffLaramy** [comment]
Hello Joseph,

Thank you for the quick response.  Juli and Glenn use the tool on a regular basis and we really appreciate you folks being on top of things and quick to respond.  Makes life easier on this end.

Thanks again and take care,

--Jeff

________________________________
