### ISSUE TITLE
"No suitable primary station locations were found by the APT..."

### ISSUE THREAD

**Issue by MKellGRWA** [jDeters-USACE/Antecedent-Precipitation-Tool#25]
Recently when I try to use the APT it will seem to be functioning properly until it starts repeating the following text indefinitely.

"Searching for primary station...
No suitable primary station locations were found by the APT..."

![APT Error](https://user-images.githubusercontent.com/130095234/230470524-d8451a25-9035-44a8-bcb1-b47ea556c1b4.jpg)

Attached is a screenshot of the input and error I've been running into.

I've attempted running the tool with several different locations and they all ended with the same error.
Any help with resolving this issue would be greatly appreciated.

**Comment by jlgutenson** [comment]
Hi @MKellGRWA, 

Sorry to hear you're having APT troubles!

I haven't been able to replicate the problem you're having on my instance of the APT. This suggests this is a local issue on your machine. 

Let's try deleting the files in your "Antecedent Precipitation Tool\cached" directory. 

Just let me know if that does the trick.

Thanks,
Joseph Gutenson

**Comment by MKellGRWA** [comment]
Unfortunately deleting the files in the cached directory and running the tool again led to the same result.

I also downloaded a fresh copy of APT v1.0.23 and I'm still receiving the same error.

For other context, it is in a folder on my desktop and I'm running it through "main_ex.exe" as trying to open "Antecedent Precipitation Tool.exe" results in a window that immediately closes.

I have successfully ran the tool on this version and computer before, and my coworker is having the same issue on a different computer.

**Comment by jlgutenson** [comment]
Ok, thank you for trying that!

This seems to be an issue with your organizations IT network. Specifically, there may be https calls that are being made to NOAA's servers using the Ulmo library (https://ulmo.readthedocs.io/en/latest/api.html#module-ulmo.ncdc.ghcn_daily) that are being blocked by the network. 

You will probably need to work with your IT department so that they can whitelist the calls being made by the APT.

**Comment by MKellGRWA** [comment]
After working with my organizations tech support and some trial and error, I have found that the issue is not with our network blocking anything as I can successfully run the program with some of the dates.

![Outputting Correctly](https://user-images.githubusercontent.com/130095234/230943938-5ae7c07b-c5ba-43f8-b90c-8ff01d60cbf6.jpg)

Inputting any of the dates after the ones used above individually or in combination results in the same error.

After more trial and error I found that inputting any date 2010-07-16 or earlier will result in the APT outputting correctly,

![2010-07-16 Output](https://user-images.githubusercontent.com/130095234/230944795-967f0a63-8d55-4339-a35c-0cc194d295f4.jpg)

while any date 2010-07-17 or later results in the error

![2010-07-17 Error](https://user-images.githubusercontent.com/130095234/230944923-3cf4e4ec-e069-4c39-ae87-5f514e6f0798.jpg)

This issue also appears to not be region specific, as I still receive the same error in other locations if I use those more recent dates.

![Georgia Error](https://user-images.githubusercontent.com/130095234/230949784-9e7cf3c1-0e53-40e2-9d96-1404611c504e.jpg)

**Comment by jlgutenson** [comment]
Hi @MKellGRWA, 

Thank you for the detailed reply! 

After looking into your issue further, I think I've discovered the problem. 

If you access your APT results in your "Antecedent Precipitation Tool\Outputs\v1_0_22\31.676850, -82.142761" directory you'll see that a portion of the dates have been output for your observation point. The rest of the dates, such as 2017-09-09, do not exist because the APT was unable to find a suitable primary station, due to sparse data. 

Unfortunately, there isn't a workaround for this because the precipitation data has not met the APT's requirements. 

For additional dates, such as 2022-04-26, there may be sufficient data for the site but the APT processing was interrupted by the failed 2017-09-09 run and may be ran in a separate APT analysis. 

Thanks,
Joseph Gutenson

**Comment by MKellGRWA** [comment]
I have since been able to run the apt successfully for the dates I've had trouble with. I still on occasion run into the same error, but its seems the clearing the cache and deleting or renaming the output folder now fixes it on the next attempt.
